# Generated by Django 2.2.3 on 2019-07-14 19:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fenotipos',
            managers=[
                ('datas', django.db.models.manager.Manager()),
            ],
        ),
    ]
